apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secret
spec:
  replicas: 1
  selector:
    matchLabels:
        app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: secrets
            mountPath: "/mnt/secrets"
            readOnly: true
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io 
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aks-secret-nf"
            nodePublishSecretRef:
              name: secrets-store-creds
