apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-secret-nf
spec:
  provider: azure
  parameters:
    keyvaultName: aks-secret-nf
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret
        - |
          objectName: secret2
          objectType: secret
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
