apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: key-vault-secret
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "nf425csi"
    objects:  |
      array:
        - |
          objectName: secret-425
          objectType: secret
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
  secretObjects:
  - secretName: key-vault-secret
    type: Opaque
    data:
    - objectName: secret-425
      key: secret-content